### ISSUE TITLE
App support issues

### ISSUE THREAD

**Issue by VasilisKos** [sapphirepro/screenwidget-translations#33]
1. Translations are not updated in the app, thought merged long ago. Why?
2.  Updates are uploaded on Google Play, with no changelog. Why?
Is this app supported anymore, or is it just typically maintained? 🤨

**Comment by sapphirepro** [comment]
Hello. There are no major translation changes, therefore was not pushed here. But will update soon. I will update repository within 24 hours.

Regarding Play Store, all fixes recently related to visual instructions and Android 13 bug fixes. That's all. A big update will happen within a week, then will be a big change log. So app is well maintained and not abandoned.

**Comment by sapphirepro** [comment]
Latest translations uploaded. Therefore issue being closed as translation files being updated to latest release. If you want to make any modifications, open a pull request.
